name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 9 * * *'

jobs:
  host:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    if: ${{ github.repository == 'ruby/digest' || github.event_name != 'schedule' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        ruby:
        - '3.0'
        include:

        - { os: ubuntu-20.04,   ruby: truffleruby }


    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache

      - run: ruby --version

      - run: bundle exec rake compile

      - run: bundle exec rake build

      - run: bundle exec rake test

      - name: Integration test
        run: bundle exec rake check
        # continue-on-error: ${{ matrix.ignore-pkg-error || (matrix.ruby == 'debug') }}
